feat: new build

diff --git a/.github/workflows/check-dist.yaml b/.github/workflows/check-dist.yaml
--- a/.github/workflows/check-dist.yaml
+++ b/.github/workflows/check-dist.yaml
@@ -38,26 +38,32 @@ jobs:
           node-version-file: .node-version
           cache: pnpm
 
-      - name: Install Dependencies
+      - name: Install dependencies
         run: pnpm install
 
       - name: Build dist/ Directory
         run: pnpm bundle
 
-      # This will fail the workflow if the PR wasn't created by Dependabot.
-      - name: Compare Directories
+      # This will fail the workflow if the `dist/` directory is different than
+      # expected.
+      - name: Compare directories
         id: diff
         run: |
+          if [ ! -d dist/ ]; then
+            echo "Expected dist/ directory does not exist.  See status below:"
+            ls -la ./
+            exit 1
+          fi
           if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
             echo "Detected uncommitted changes after build. See status below:"
             git diff --ignore-space-at-eol --text dist/
             exit 1
           fi
 
-      # If `dist/` was different than expected, and this was not a Dependabot
-      # PR, upload the expected version as a workflow artifact.
+      # If `dist/` was different than expected, upload the expected version as a
+      # workflow artifact.
       - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload Artifact
+        name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: dist
